# BEGIN_KITTY_FONTS
font_family      family="Hack Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# custom_configuration
font_size 14.0
window_margin_width	10
background_image	~/.config/kitty/sunlight-shining-single-mountain-top-sunset-with-dark-cloudy-sky.jpg
background_image_layout	scaled
background_tint         0.77
background_tint_gaps    -10.0

window_border_width     1pt
active_border_color     #44ffff
single_window_margin_width 4
macos_option_as_alt no
tab_bar_style       powerline
tab_powerline_style slanted

remember_window_position yes
confirm_os_window_close 1
